# Generated by Django 4.0.4 on 2022-05-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('key_person', models.CharField(max_length=64)),
                ('involving_industry', models.CharField(max_length=64)),
                ('phone_no', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pf_no', models.CharField(max_length=30)),
                ('head_office_address', models.TextField()),
                ('pan_no', models.CharField(max_length=10, unique=True)),
                ('tin_no', models.PositiveBigIntegerField()),
                ('registration_no', models.CharField(max_length=50)),
                ('key_person_address', models.TextField()),
                ('key_person_phone_no', models.PositiveBigIntegerField()),
                ('key_designation', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company')),
            ],
        ),
    ]
