# Generated by Django 4.0.4 on 2022-08-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company', serialize=False, to='api.company')),
                ('address', models.TextField()),
                ('key_person', models.CharField(blank=True, max_length=64)),
                ('involving_industry', models.CharField(blank=True, max_length=64)),
                ('phone_no', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pf_no', models.CharField(max_length=30)),
                ('esi_no', models.PositiveBigIntegerField()),
                ('head_office_address', models.TextField()),
                ('pan_no', models.CharField(max_length=10, unique=True)),
                ('tin_no', models.CharField(blank=True, max_length=11)),
                ('registration_no', models.CharField(blank=True, max_length=50)),
                ('registration_date', models.DateField()),
            ],
        ),
    ]
